In [2]:
import numpy as np 



In [4]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((7,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [8]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [14]:
a = np.array([[1,2,3],[4,5,6],[1,1,1]])
b = np.array([[2,3,4],[5,6,7],[1,1,1]])

print(np.dot(a,b))

[[15 18 21]
 [39 48 57]
 [ 8 10 12]]


In [16]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(np.dot(A, B))   # Matrix multiplication
print(A.T)            # Transpose


[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


In [17]:
a = np.array([1,2,3,4,5,6,7,8])

In [18]:
a.shape

(8,)

In [19]:
a[:3]

array([1, 2, 3])

In [21]:
a = np.array([[1,2,3,4],[2,3,4,5],[3,3,6,6]])

In [22]:
a.ndim

2

In [23]:
print(a)

[[1 2 3 4]
 [2 3 4 5]
 [3 3 6 6]]


In [26]:
print(a)
print(a.min())
print(a.max())
print(a.mean())
print(a.shape)

[[1 2 3 4]
 [2 3 4 5]
 [3 3 6 6]]
1
6
3.5
(3, 4)


In [27]:
a.sort

<function ndarray.sort>